-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) AS YEAR, 
MONTH(A.SALES_DATE) AS MONTH, B.GENDER, 
COUNT(DISTINCT B.USER_ID) AS USERS
FROM ONLINE_SALE A JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, B.GENDER
ORDER BY YEAR, MONTH, B.GENDER