-- 코드를 입력하세요
SELECT USU.USER_ID, USU.NICKNAME, 
CONCAT(USU.CITY,' ', USU.STREET_ADDRESS1,' ', USU.STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(USU.TLNO, 3),'-',MID(USU.TLNO, 4, 4),'-',RIGHT(USU.TLNO, 4)) AS 전화번호
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER USU
ON UGB.WRITER_ID = USU.USER_ID
GROUP BY USU.USER_ID
HAVING COUNT(*)>=3
ORDER BY USU.USER_ID DESC
;