-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(ABS(DATEDIFF(START_DATE,END_DATE)))+1,1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
;

-- 날짜 사이 기간을 구하려면 DATEDIFF(START_DATE,END_DATE) 이렇게 쓰면 됨 !
-- GROUP BY 에서 조건을 주고싶으면 HAVING 을 쓰면된당
