SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B_S.SALES*PRICE)
FROM BOOK_SALES B_S,BOOK B,AUTHOR A
WHERE 
    B_S.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = A.AUTHOR_ID
    AND (YEAR(B_S.SALES_DATE) = 2022 AND MONTH(B_S.SALES_DATE) = 1)
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY 1 ASC, 3 DESC;