-- 코드를 입력하세요
SELECT FO.PRODUCT_ID , PRODUCT_NAME ,SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_ORDER FO,FOOD_PRODUCT FP
WHERE FO.PRODUCT_ID = FP.PRODUCT_ID
AND PRODUCE_DATE LIKE '2022-05%'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , PRODUCT_ID
;