SELECT IT.ITEM_ID,II.ITEM_NAME,II.RARITY
  FROM  ITEM_TREE AS IT
 INNER  
  JOIN  ITEM_INFO AS II
    ON  IT.ITEM_ID = II.ITEM_ID
 WHERE  PARENT_ITEM_ID IN (SELECT  ITEM_ID
                             FROM  ITEM_INFO
                            WHERE  RARITY='RARE')
 ORDER BY  IT.ITEM_ID DESC;