-- 코드를 입력하세요
SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, DR.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
  FROM PATIENT PT, DOCTOR DR, APPOINTMENT AP
  WHERE PT.PT_NO = AP.PT_NO AND DR.MCDP_CD = AP.MCDP_CD AND DR.DR_ID = AP.MDDR_ID
        AND AP.APNT_CNCL_YN = 'N' AND AP.MCDP_CD = 'CS'
        AND DATE_FORMAT(APNT_YMD,'%Y%m%d') = '20220413'
  ORDER BY AP.APNT_YMD ASC;